INSERT_COMPANY_DETAILS = "INSERT INTO company_details(company,ceo,grade,division,s1,s2,s3,s4,s5,s6,balance,strikes,remarks,ID) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
SELECT_ALL_COMPANY_DETAILS = "SELECT * FROM company_details"
SORT_STUDNETS = "SELECT * FROM company_details WHERE grade=? AND division=?"
SELECT_ALL_WITH_CEO = "SELECT * FROM company_details WHERE ceo=?"
GET_BALANCE = "SELECT balance FROM company_details WHERE ID=?"
UPDATE_COIN = "UPDATE company_details SET balance=? WHERE ID=?"
GET_STRIKES = "SELECT strikes FROM company_details WHERE ID=?"
UPDATE_STRIKES = "UPDATE company_details SET strikes=?, remarks=? WHERE ID=?"
SELECT_BLACK_COMPANY_DETAILS = "SELECT * FROM company_details WHERE strikes >= ?"
